name: repeatmodeler_builddatabase
description: Build a database for a genome FASTA file 
keywords:
  - RepeatModeler
  - fasta
  - repeat
  - database
tools:
  - repeatmodeler:
      description: RepeatModeler is a de-novo repeat family identification and modeling package.
      homepage: http://www.repeatmasker.org/RepeatModeler/
      documentation: http://www.repeatmasker.org/RepeatModeler/
      tool_dev_url: https://github.com/Dfam-consortium/RepeatModeler
      doi: ""
      licence: ['Open Software License v2.1']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.{fa,fasta}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - db:
      type: directory
      description: Output directory containing genome index files
      pattern: "*"

authors:
  - "@aleksandrabliznina"